vich_uploader:
    db_driver: orm

    mappings:
       product_image:
           uri_prefix: '%product_image%'
           upload_destination: '%kernel.project_dir%/public%product_image%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false
