index:
   path: /
   controller: App\Controller\DefaultController::index

club:
   path: /club
   controller: App\Controller\ClubController::club

equipement: 
   path: /equipement
   controller: App\Controller\EquipementController::equipement  

nutrition: 
   path: /nutrition
   controller: App\Controller\NutritionController::nutrition